import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { Activity, AlertCircle, CheckCircle2, ChevronRight, FileCode2, Globe2, Search, ShieldCheck, TriangleAlert } from "lucide-react";
import { adminService } from "@/services/adminService";

type Severity = "critical" | "warning" | "info";
type SeoIssue = { contentName: string; contentType: "package" | "blog"; contentId: string; content: string; seoCategory: string; severity: Severity; recommendation: string; field: string; status: string };
const scoreClass = (score: number) => score >= 90 ? "text-emerald-500" : score >= 70 ? "text-amber-500" : "text-red-500";
const scoreLabel = (score: number) => score >= 90 ? "Excellent" : score >= 70 ? "Needs improvement" : "Critical";
const severityClass: Record<Severity, string> = { critical: "bg-red-500/10 text-red-600", warning: "bg-amber-500/10 text-amber-600", info: "bg-blue-500/10 text-blue-600" };

function ScoreCard({ label, score, icon: Icon }: { label: string; score: number; icon: typeof Activity }) {
  return <div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-medium text-muted-foreground">{label}</p><Icon className="h-5 w-5 text-primary" /></div><div className="mt-4 flex items-end gap-2"><strong className={`text-3xl ${scoreClass(score)}`}>{score}%</strong><span className="mb-1 text-xs text-muted-foreground">{scoreLabel(score)}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${score >= 90 ? "bg-emerald-500" : score >= 70 ? "bg-amber-500" : "bg-red-500"}`} style={{ width: `${score}%` }} /></div></div>;
}

export const SeoDashboard = () => {
  const { data, isLoading, isError } = useQuery({ queryKey: ["admin-seo-health"], queryFn: () => adminService.getSeoHealth(), staleTime: 60_000 });
  const [filter, setFilter] = useState<"all" | Severity | "package" | "blog">("all");
  const [search, setSearch] = useState("");
  const payload = data?.data;
  const issues = (payload?.issues || []) as SeoIssue[];
  const filteredIssues = useMemo(() => issues.filter((item) => (filter === "all" || item.severity === filter || item.contentType === filter) && `${item.contentName} ${item.content} ${item.seoCategory}`.toLowerCase().includes(search.toLowerCase())), [filter, issues, search]);
  if (isLoading) return <div className="flex h-[50vh] items-center justify-center"><div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent" /></div>;
  if (isError || !data?.success) return <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-6 text-red-700"><div className="flex gap-2 font-semibold"><AlertCircle />Unable to load SEO health data</div></div>;
  const scores = payload.scores || { overall: payload.healthScore, packages: payload.healthScore, blogs: payload.healthScore, technical: payload.healthScore };
  const counters = { critical: issues.filter((item) => item.severity === "critical").length, warning: issues.filter((item) => item.severity === "warning").length, info: issues.filter((item) => item.severity === "info").length };
  return <div className="space-y-6 pb-10"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">SEO Health</h1><p className="mt-1 text-muted-foreground">Content, technical, and indexing signals in one workspace.</p></div><p className="text-xs text-muted-foreground">Last analysed {new Date(payload.lastChecked).toLocaleString()}</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} className="rounded-2xl border border-border bg-card p-5 text-center shadow-sm"><div className={`mx-auto grid h-24 w-24 place-items-center rounded-full border-8 ${scores.overall >= 90 ? "border-emerald-500" : scores.overall >= 70 ? "border-amber-500" : "border-red-500"}`}><strong className="text-2xl">{scores.overall}%</strong></div><p className="mt-3 text-sm font-semibold">Overall website SEO</p><p className={`text-xs ${scoreClass(scores.overall)}`}>{scoreLabel(scores.overall)}</p></motion.div><ScoreCard label="Packages SEO" score={scores.packages} icon={Globe2} /><ScoreCard label="Blogs SEO" score={scores.blogs} icon={FileCode2} /><ScoreCard label="Technical SEO" score={scores.technical} icon={ShieldCheck} /></div>
    <div className="grid gap-4 md:grid-cols-3">{(["critical", "warning", "info"] as Severity[]).map((severity) => <button key={severity} onClick={() => setFilter(severity)} className="rounded-2xl border border-border bg-card p-4 text-left shadow-sm transition hover:border-primary/40"><span className={`inline-flex rounded-full px-2 py-1 text-xs font-semibold ${severityClass[severity]}`}>{severity}</span><p className="mt-2 text-3xl font-bold">{counters[severity]}</p><p className="text-sm text-muted-foreground">{severity === "info" ? "Optimisation opportunities" : `${severity[0].toUpperCase() + severity.slice(1)} issues`}</p></button>)}</div>
    <section className="rounded-2xl border border-border bg-card shadow-sm"><div className="flex flex-col gap-3 border-b border-border p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-semibold">SEO issue centre</h2><p className="text-sm text-muted-foreground">Prioritised recommendations across packages and blogs.</p></div><div className="flex flex-wrap gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search issues" className="h-9 rounded-lg border bg-background pl-9 pr-3 text-sm" /></div>{(["all", "package", "blog", "critical", "warning"] as const).map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-lg px-3 py-2 text-xs font-medium ${filter === value ? "bg-primary text-primary-foreground" : "bg-muted hover:bg-muted/70"}`}>{value}</button>)}</div></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-muted/40 text-left text-xs text-muted-foreground"><tr><th className="p-4">Content</th><th>Issue</th><th>Severity</th><th>SEO category</th><th>Recommendation</th><th className="p-4">Action</th></tr></thead><tbody>{filteredIssues.map((item, index) => <tr key={`${item.contentId}-${item.content}-${index}`} className="border-t border-border"><td className="p-4"><p className="font-medium">{item.contentName}</p><p className="text-xs text-muted-foreground">{item.contentType}</p></td><td>{item.content}</td><td><span className={`rounded-full px-2 py-1 text-xs font-medium ${severityClass[item.severity]}`}>{item.severity}</span></td><td>{item.seoCategory}</td><td className="max-w-xs text-muted-foreground">{item.recommendation}</td><td className="p-4"><Link to={item.contentType === "package" ? "/admin/packages" : "/admin/blogs"} search={{ seoField: item.field } as never} className="inline-flex items-center gap-1 text-primary hover:underline">Fix now <ChevronRight className="h-3 w-3" /></Link></td></tr>)}{!filteredIssues.length && <tr><td colSpan={6} className="p-10 text-center text-muted-foreground"><CheckCircle2 className="mx-auto mb-2 h-6 w-6 text-emerald-500" />No matching issues.</td></tr>}</tbody></table></div></section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="flex items-center gap-2 font-semibold"><Activity className="h-4 w-4 text-primary" />Technical SEO</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{(payload.technicalChecks || []).map((item: { name: string; status: string }) => <div key={item.name} className="flex items-center justify-between rounded-lg bg-muted/40 px-3 py-2"><span className="text-sm">{item.name}</span><span className={item.status === "healthy" ? "text-emerald-600" : "text-amber-600"}>{item.status === "healthy" ? "Healthy" : "Warning"}</span></div>)}</div></section><section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="flex items-center gap-2 font-semibold"><TriangleAlert className="h-4 w-4 text-primary" />Google Search Console</h2><p className="mt-1 text-sm text-muted-foreground">Connection-ready reporting placeholders.</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-lg bg-muted/40 p-3"><p className="text-muted-foreground">Indexed pages</p><strong className="text-xl">{payload.searchConsole?.indexedPages ?? "—"}</strong></div><div className="rounded-lg bg-muted/40 p-3"><p className="text-muted-foreground">Pages with errors</p><strong className="text-xl">{payload.searchConsole?.pagesWithErrors ?? "—"}</strong></div><div className="rounded-lg bg-muted/40 p-3"><p className="text-muted-foreground">Sitemap</p><strong>{payload.searchConsole?.sitemapStatus ?? "Ready"}</strong></div><div className="rounded-lg bg-muted/40 p-3"><p className="text-muted-foreground">CTR / position</p><strong>Connect GSC</strong></div></div></section></div></div>;
};
