import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Copy, Plus, Trash2 } from "lucide-react";
import { adminService, ItineraryDayItem } from "@/services/adminService";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

const emptyDay = (dayNumber: number): Partial<ItineraryDayItem> => ({ dayNumber, title: "", altitude: "", meals: "", accommodation: "", hours: "", distance: "", description: "", checklist: [], gallery: [] });
export function StructuredItineraryTab({ packageId }: { packageId: string }) {
  const qc = useQueryClient(); const [draft, setDraft] = useState<Partial<ItineraryDayItem> | null>(null);
  const query = useQuery({ queryKey: ["itinerary-days", packageId], queryFn: () => adminService.getItineraryDays(packageId), enabled: Boolean(packageId) });
  const days = query.data?.data || []; const refresh = () => qc.invalidateQueries({ queryKey: ["itinerary-days", packageId] });
  const save = useMutation({ mutationFn: () => draft?.id || draft?._id ? adminService.updateItineraryDay(String(draft.id || draft._id), draft) : adminService.createItineraryDay(packageId, draft || {}), onSuccess: () => { toast.success("Itinerary day saved"); setDraft(null); refresh(); } });
  const remove = useMutation({ mutationFn: (id: string) => adminService.deleteItineraryDay(id), onSuccess: refresh }); const duplicate = useMutation({ mutationFn: (id: string) => adminService.duplicateItineraryDay(id), onSuccess: refresh });
  if (!packageId) return <p className="rounded-xl border p-6 text-sm text-muted-foreground">Save the package first, then add structured itinerary days.</p>;
  return <div className="space-y-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Itinerary days</h2><p className="text-sm text-muted-foreground">Manage every day separately. Changes are reflected in the live preview.</p></div><Button type="button" onClick={() => setDraft(emptyDay(days.length + 1))}><Plus className="h-4 w-4" /> Add day</Button></div>{draft && <div className="grid gap-3 rounded-2xl border bg-muted/20 p-5 md:grid-cols-2"><Input type="number" value={draft.dayNumber || ""} onChange={(e) => setDraft({ ...draft, dayNumber: Number(e.target.value) })} placeholder="Day number" /><Input value={draft.title || ""} onChange={(e) => setDraft({ ...draft, title: e.target.value })} placeholder="Title" /><Input value={draft.altitude || ""} onChange={(e) => setDraft({ ...draft, altitude: e.target.value })} placeholder="Altitude" /><Input value={draft.meals || ""} onChange={(e) => setDraft({ ...draft, meals: e.target.value })} placeholder="Meals" /><Input value={draft.accommodation || ""} onChange={(e) => setDraft({ ...draft, accommodation: e.target.value })} placeholder="Accommodation / lodge" /><Input value={draft.hours || ""} onChange={(e) => setDraft({ ...draft, hours: e.target.value })} placeholder="Walking hours" /><Input value={draft.distance || ""} onChange={(e) => setDraft({ ...draft, distance: e.target.value })} placeholder="Distance" /><Input value={(draft.checklist || []).join("\n")} onChange={(e) => setDraft({ ...draft, checklist: e.target.value.split("\n").filter(Boolean) })} placeholder="Checklist (one item per line)" /><Textarea className="md:col-span-2" value={draft.description || ""} onChange={(e) => setDraft({ ...draft, description: e.target.value })} placeholder="Detailed description" /><div className="md:col-span-2 flex gap-2"><Button type="button" onClick={() => save.mutate()} disabled={save.isPending}>Save day</Button><Button type="button" variant="outline" onClick={() => setDraft(null)}>Cancel</Button></div></div>}{query.isLoading ? <p>Loading itinerary…</p> : <div className="space-y-3">{days.map((day) => <article key={day.id || day._id} className="rounded-2xl border p-4"><div className="flex justify-between gap-4"><button type="button" className="text-left" onClick={() => setDraft(day)}><p className="text-xs font-bold text-primary">DAY {day.dayNumber}</p><h3 className="font-semibold">{day.title}</h3><p className="text-sm text-muted-foreground">{day.altitude} · {day.meals} · {day.accommodation}</p></button><div className="flex gap-2"><Button size="icon" variant="outline" onClick={() => duplicate.mutate(String(day.id || day._id))}><Copy className="h-4 w-4" /></Button><Button size="icon" variant="outline" onClick={() => remove.mutate(String(day.id || day._id))}><Trash2 className="h-4 w-4 text-red-600" /></Button></div></div>{day.description && <p className="mt-3 text-sm text-muted-foreground">{day.description}</p>}</article>)}</div>}</div>;
}
